### ISSUE TITLE
Determine what information we need to collect for database

### ISSUE THREAD

**Issue by Lorsen** [ReceiptImage-ProcessingTool/OPR_Research#7]

**Comment by Lorsen** [comment]
1) What do we need from image?
2) What do we need for a user account?

**Comment by laxmatt08** [comment]
To create a Schedule A we would need full legal name and ss#. I think for our app it will be hard for us to convince someone to give us that info. I say we ask for First, Last, email, and 4 digit pin for a password to use the app locally.
